# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/q273/pokemon_ar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/q273/pokemon_ar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q273/pokemon_ar/CMakeFiles /home/q273/pokemon_ar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q273/pokemon_ar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.out

# Build rule for target.
main.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.out
.PHONY : main.out

# fast build rule for target.
main.out/fast:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/build
.PHONY : main.out/fast

project/src/AnimModel.o: project/src/AnimModel.cpp.o

.PHONY : project/src/AnimModel.o

# target to build an object file
project/src/AnimModel.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/AnimModel.cpp.o
.PHONY : project/src/AnimModel.cpp.o

project/src/AnimModel.i: project/src/AnimModel.cpp.i

.PHONY : project/src/AnimModel.i

# target to preprocess a source file
project/src/AnimModel.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/AnimModel.cpp.i
.PHONY : project/src/AnimModel.cpp.i

project/src/AnimModel.s: project/src/AnimModel.cpp.s

.PHONY : project/src/AnimModel.s

# target to generate assembly for a file
project/src/AnimModel.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/AnimModel.cpp.s
.PHONY : project/src/AnimModel.cpp.s

project/src/Button.o: project/src/Button.cpp.o

.PHONY : project/src/Button.o

# target to build an object file
project/src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Button.cpp.o
.PHONY : project/src/Button.cpp.o

project/src/Button.i: project/src/Button.cpp.i

.PHONY : project/src/Button.i

# target to preprocess a source file
project/src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Button.cpp.i
.PHONY : project/src/Button.cpp.i

project/src/Button.s: project/src/Button.cpp.s

.PHONY : project/src/Button.s

# target to generate assembly for a file
project/src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Button.cpp.s
.PHONY : project/src/Button.cpp.s

project/src/ButtonFunctions.o: project/src/ButtonFunctions.cpp.o

.PHONY : project/src/ButtonFunctions.o

# target to build an object file
project/src/ButtonFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ButtonFunctions.cpp.o
.PHONY : project/src/ButtonFunctions.cpp.o

project/src/ButtonFunctions.i: project/src/ButtonFunctions.cpp.i

.PHONY : project/src/ButtonFunctions.i

# target to preprocess a source file
project/src/ButtonFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ButtonFunctions.cpp.i
.PHONY : project/src/ButtonFunctions.cpp.i

project/src/ButtonFunctions.s: project/src/ButtonFunctions.cpp.s

.PHONY : project/src/ButtonFunctions.s

# target to generate assembly for a file
project/src/ButtonFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ButtonFunctions.cpp.s
.PHONY : project/src/ButtonFunctions.cpp.s

project/src/Cake.o: project/src/Cake.cpp.o

.PHONY : project/src/Cake.o

# target to build an object file
project/src/Cake.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Cake.cpp.o
.PHONY : project/src/Cake.cpp.o

project/src/Cake.i: project/src/Cake.cpp.i

.PHONY : project/src/Cake.i

# target to preprocess a source file
project/src/Cake.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Cake.cpp.i
.PHONY : project/src/Cake.cpp.i

project/src/Cake.s: project/src/Cake.cpp.s

.PHONY : project/src/Cake.s

# target to generate assembly for a file
project/src/Cake.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Cake.cpp.s
.PHONY : project/src/Cake.cpp.s

project/src/Game.o: project/src/Game.cpp.o

.PHONY : project/src/Game.o

# target to build an object file
project/src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Game.cpp.o
.PHONY : project/src/Game.cpp.o

project/src/Game.i: project/src/Game.cpp.i

.PHONY : project/src/Game.i

# target to preprocess a source file
project/src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Game.cpp.i
.PHONY : project/src/Game.cpp.i

project/src/Game.s: project/src/Game.cpp.s

.PHONY : project/src/Game.s

# target to generate assembly for a file
project/src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Game.cpp.s
.PHONY : project/src/Game.cpp.s

project/src/GameWindow.o: project/src/GameWindow.cpp.o

.PHONY : project/src/GameWindow.o

# target to build an object file
project/src/GameWindow.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/GameWindow.cpp.o
.PHONY : project/src/GameWindow.cpp.o

project/src/GameWindow.i: project/src/GameWindow.cpp.i

.PHONY : project/src/GameWindow.i

# target to preprocess a source file
project/src/GameWindow.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/GameWindow.cpp.i
.PHONY : project/src/GameWindow.cpp.i

project/src/GameWindow.s: project/src/GameWindow.cpp.s

.PHONY : project/src/GameWindow.s

# target to generate assembly for a file
project/src/GameWindow.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/GameWindow.cpp.s
.PHONY : project/src/GameWindow.cpp.s

project/src/Interfaces.o: project/src/Interfaces.cpp.o

.PHONY : project/src/Interfaces.o

# target to build an object file
project/src/Interfaces.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Interfaces.cpp.o
.PHONY : project/src/Interfaces.cpp.o

project/src/Interfaces.i: project/src/Interfaces.cpp.i

.PHONY : project/src/Interfaces.i

# target to preprocess a source file
project/src/Interfaces.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Interfaces.cpp.i
.PHONY : project/src/Interfaces.cpp.i

project/src/Interfaces.s: project/src/Interfaces.cpp.s

.PHONY : project/src/Interfaces.s

# target to generate assembly for a file
project/src/Interfaces.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Interfaces.cpp.s
.PHONY : project/src/Interfaces.cpp.s

project/src/MarkerDetector.o: project/src/MarkerDetector.cpp.o

.PHONY : project/src/MarkerDetector.o

# target to build an object file
project/src/MarkerDetector.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MarkerDetector.cpp.o
.PHONY : project/src/MarkerDetector.cpp.o

project/src/MarkerDetector.i: project/src/MarkerDetector.cpp.i

.PHONY : project/src/MarkerDetector.i

# target to preprocess a source file
project/src/MarkerDetector.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MarkerDetector.cpp.i
.PHONY : project/src/MarkerDetector.cpp.i

project/src/MarkerDetector.s: project/src/MarkerDetector.cpp.s

.PHONY : project/src/MarkerDetector.s

# target to generate assembly for a file
project/src/MarkerDetector.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MarkerDetector.cpp.s
.PHONY : project/src/MarkerDetector.cpp.s

project/src/Mesh.o: project/src/Mesh.cpp.o

.PHONY : project/src/Mesh.o

# target to build an object file
project/src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Mesh.cpp.o
.PHONY : project/src/Mesh.cpp.o

project/src/Mesh.i: project/src/Mesh.cpp.i

.PHONY : project/src/Mesh.i

# target to preprocess a source file
project/src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Mesh.cpp.i
.PHONY : project/src/Mesh.cpp.i

project/src/Mesh.s: project/src/Mesh.cpp.s

.PHONY : project/src/Mesh.s

# target to generate assembly for a file
project/src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Mesh.cpp.s
.PHONY : project/src/Mesh.cpp.s

project/src/Model.o: project/src/Model.cpp.o

.PHONY : project/src/Model.o

# target to build an object file
project/src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Model.cpp.o
.PHONY : project/src/Model.cpp.o

project/src/Model.i: project/src/Model.cpp.i

.PHONY : project/src/Model.i

# target to preprocess a source file
project/src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Model.cpp.i
.PHONY : project/src/Model.cpp.i

project/src/Model.s: project/src/Model.cpp.s

.PHONY : project/src/Model.s

# target to generate assembly for a file
project/src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Model.cpp.s
.PHONY : project/src/Model.cpp.s

project/src/MovingPicture.o: project/src/MovingPicture.cpp.o

.PHONY : project/src/MovingPicture.o

# target to build an object file
project/src/MovingPicture.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MovingPicture.cpp.o
.PHONY : project/src/MovingPicture.cpp.o

project/src/MovingPicture.i: project/src/MovingPicture.cpp.i

.PHONY : project/src/MovingPicture.i

# target to preprocess a source file
project/src/MovingPicture.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MovingPicture.cpp.i
.PHONY : project/src/MovingPicture.cpp.i

project/src/MovingPicture.s: project/src/MovingPicture.cpp.s

.PHONY : project/src/MovingPicture.s

# target to generate assembly for a file
project/src/MovingPicture.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/MovingPicture.cpp.s
.PHONY : project/src/MovingPicture.cpp.s

project/src/Picture.o: project/src/Picture.cpp.o

.PHONY : project/src/Picture.o

# target to build an object file
project/src/Picture.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Picture.cpp.o
.PHONY : project/src/Picture.cpp.o

project/src/Picture.i: project/src/Picture.cpp.i

.PHONY : project/src/Picture.i

# target to preprocess a source file
project/src/Picture.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Picture.cpp.i
.PHONY : project/src/Picture.cpp.i

project/src/Picture.s: project/src/Picture.cpp.s

.PHONY : project/src/Picture.s

# target to generate assembly for a file
project/src/Picture.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Picture.cpp.s
.PHONY : project/src/Picture.cpp.s

project/src/ShaderProgram.o: project/src/ShaderProgram.cpp.o

.PHONY : project/src/ShaderProgram.o

# target to build an object file
project/src/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ShaderProgram.cpp.o
.PHONY : project/src/ShaderProgram.cpp.o

project/src/ShaderProgram.i: project/src/ShaderProgram.cpp.i

.PHONY : project/src/ShaderProgram.i

# target to preprocess a source file
project/src/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ShaderProgram.cpp.i
.PHONY : project/src/ShaderProgram.cpp.i

project/src/ShaderProgram.s: project/src/ShaderProgram.cpp.s

.PHONY : project/src/ShaderProgram.s

# target to generate assembly for a file
project/src/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/ShaderProgram.cpp.s
.PHONY : project/src/ShaderProgram.cpp.s

project/src/States.o: project/src/States.cpp.o

.PHONY : project/src/States.o

# target to build an object file
project/src/States.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/States.cpp.o
.PHONY : project/src/States.cpp.o

project/src/States.i: project/src/States.cpp.i

.PHONY : project/src/States.i

# target to preprocess a source file
project/src/States.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/States.cpp.i
.PHONY : project/src/States.cpp.i

project/src/States.s: project/src/States.cpp.s

.PHONY : project/src/States.s

# target to generate assembly for a file
project/src/States.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/States.cpp.s
.PHONY : project/src/States.cpp.s

project/src/Utils.o: project/src/Utils.cpp.o

.PHONY : project/src/Utils.o

# target to build an object file
project/src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Utils.cpp.o
.PHONY : project/src/Utils.cpp.o

project/src/Utils.i: project/src/Utils.cpp.i

.PHONY : project/src/Utils.i

# target to preprocess a source file
project/src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Utils.cpp.i
.PHONY : project/src/Utils.cpp.i

project/src/Utils.s: project/src/Utils.cpp.s

.PHONY : project/src/Utils.s

# target to generate assembly for a file
project/src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/Utils.cpp.s
.PHONY : project/src/Utils.cpp.s

project/src/VideoStream.o: project/src/VideoStream.cpp.o

.PHONY : project/src/VideoStream.o

# target to build an object file
project/src/VideoStream.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/VideoStream.cpp.o
.PHONY : project/src/VideoStream.cpp.o

project/src/VideoStream.i: project/src/VideoStream.cpp.i

.PHONY : project/src/VideoStream.i

# target to preprocess a source file
project/src/VideoStream.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/VideoStream.cpp.i
.PHONY : project/src/VideoStream.cpp.i

project/src/VideoStream.s: project/src/VideoStream.cpp.s

.PHONY : project/src/VideoStream.s

# target to generate assembly for a file
project/src/VideoStream.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/VideoStream.cpp.s
.PHONY : project/src/VideoStream.cpp.s

project/src/main.o: project/src/main.cpp.o

.PHONY : project/src/main.o

# target to build an object file
project/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.cpp.o
.PHONY : project/src/main.cpp.o

project/src/main.i: project/src/main.cpp.i

.PHONY : project/src/main.i

# target to preprocess a source file
project/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.cpp.i
.PHONY : project/src/main.cpp.i

project/src/main.s: project/src/main.cpp.s

.PHONY : project/src/main.s

# target to generate assembly for a file
project/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/main.cpp.s
.PHONY : project/src/main.cpp.s

project/src/math_3d.o: project/src/math_3d.cpp.o

.PHONY : project/src/math_3d.o

# target to build an object file
project/src/math_3d.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/math_3d.cpp.o
.PHONY : project/src/math_3d.cpp.o

project/src/math_3d.i: project/src/math_3d.cpp.i

.PHONY : project/src/math_3d.i

# target to preprocess a source file
project/src/math_3d.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/math_3d.cpp.i
.PHONY : project/src/math_3d.cpp.i

project/src/math_3d.s: project/src/math_3d.cpp.s

.PHONY : project/src/math_3d.s

# target to generate assembly for a file
project/src/math_3d.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/project/src/math_3d.cpp.s
.PHONY : project/src/math_3d.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main.out"
	@echo "... edit_cache"
	@echo "... project/src/AnimModel.o"
	@echo "... project/src/AnimModel.i"
	@echo "... project/src/AnimModel.s"
	@echo "... project/src/Button.o"
	@echo "... project/src/Button.i"
	@echo "... project/src/Button.s"
	@echo "... project/src/ButtonFunctions.o"
	@echo "... project/src/ButtonFunctions.i"
	@echo "... project/src/ButtonFunctions.s"
	@echo "... project/src/Cake.o"
	@echo "... project/src/Cake.i"
	@echo "... project/src/Cake.s"
	@echo "... project/src/Game.o"
	@echo "... project/src/Game.i"
	@echo "... project/src/Game.s"
	@echo "... project/src/GameWindow.o"
	@echo "... project/src/GameWindow.i"
	@echo "... project/src/GameWindow.s"
	@echo "... project/src/Interfaces.o"
	@echo "... project/src/Interfaces.i"
	@echo "... project/src/Interfaces.s"
	@echo "... project/src/MarkerDetector.o"
	@echo "... project/src/MarkerDetector.i"
	@echo "... project/src/MarkerDetector.s"
	@echo "... project/src/Mesh.o"
	@echo "... project/src/Mesh.i"
	@echo "... project/src/Mesh.s"
	@echo "... project/src/Model.o"
	@echo "... project/src/Model.i"
	@echo "... project/src/Model.s"
	@echo "... project/src/MovingPicture.o"
	@echo "... project/src/MovingPicture.i"
	@echo "... project/src/MovingPicture.s"
	@echo "... project/src/Picture.o"
	@echo "... project/src/Picture.i"
	@echo "... project/src/Picture.s"
	@echo "... project/src/ShaderProgram.o"
	@echo "... project/src/ShaderProgram.i"
	@echo "... project/src/ShaderProgram.s"
	@echo "... project/src/States.o"
	@echo "... project/src/States.i"
	@echo "... project/src/States.s"
	@echo "... project/src/Utils.o"
	@echo "... project/src/Utils.i"
	@echo "... project/src/Utils.s"
	@echo "... project/src/VideoStream.o"
	@echo "... project/src/VideoStream.i"
	@echo "... project/src/VideoStream.s"
	@echo "... project/src/main.o"
	@echo "... project/src/main.i"
	@echo "... project/src/main.s"
	@echo "... project/src/math_3d.o"
	@echo "... project/src/math_3d.i"
	@echo "... project/src/math_3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

